### ISSUE TITLE
Url Website Not Found

### ISSUE THREAD

**Issue by panntod** [Arsyadam/thenextway-web#1]
can you fix the website url to visit the demo

**Comment by Arsyadam** [comment]
Hai Pandu, do you want thenextway-web site? Sure you can visit thenextway.tech, please let me know if it is  accessible thank youuu


From: Pandhu Arya
Sent: Saturday, 11 November 2023 15:58
To: Arsyadam/thenextway-web
Cc: Subscribed
Subject: [Arsyadam/thenextway-web] Url Website Not Found (Issue #1)

can you fix the website url to visit the demo

**Comment by Arsyadam** [comment]
Hai Pandu, do you want to visit thenextway-web?, Sure, this site has just been released and you can visit at [https://thenextway.tech](https://thenextway.tech), please let me know if it is accessible, thank youu

**Comment by panntod** [comment]
> Hai Pandu, do you want to visit thenextway-web?, Sure, this site has just been released and you can visit at [https://thenextway.tech](https://thenextway.tech), please let me know if it is accessible, thank youu

>Good job, but the next way logo is not visible, you can change the color to white or something like that so it can be seen

**Comment by Arsyadam** [comment]
Sure, the color theme is just fixed, how about now Pandu?

**Comment by panntod** [comment]
Nice I liked it👌
